# Generated by Django 3.2.5 on 2021-09-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_messa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messa',
        ),
    ]
